Profiles:

    FinalExamOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            FinalExam:
                Organizations:
                    - *Org1
                    - *Org2
                    # - *HP
                    # - *Amazon

    # AsusChannel:
    #     Consortium: PCXCHG
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *Asus
    #             - *Amazon
    # DellChannel:
    #     Consortium: PCXCHG
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *Dell
    #             - *Amazon
    # HPChannel:
    #     Consortium: PCXCHG
    #     Application:
    #         <<: *ApplicationDefaults
    #         Organizations:
    #             - *HP
    #             - *Amazon
Organizations:

    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP

        MSPDir: crypto-config/ordererOrganizations/FinalExam.com/msp

    - &Org1
        Name: Org1MSP
        ID: Org1MSP

        MSPDir: crypto-config/peerOrganizations/Org1.com/msp

        AnchorPeers:
            - Host: peer0.Org1.com
              Port: 7051

    - &Org2
        Name: Org2MSP
        ID: Org2MSP

        MSPDir: crypto-config/peerOrganizations/Org2.com/msp

        AnchorPeers:
            - Host: peer0.Org2.com
              Port: 7051

    # - &Dell
    #     Name: DellMSP
    #     ID: DellMSP

    #     MSPDir: crypto-config/peerOrganizations/Dell.com/msp

    #     AnchorPeers:
    #         - Host: peer0.Dell.com
    #           Port: 7051

    # - &HP
    #     Name: HPMSP
    #     ID: HPMSP

    #     MSPDir: crypto-config/peerOrganizations/HP.com/msp

    #     AnchorPeers:
    #         - Host: peer0.HP.com
    #           Port: 7051
Orderer: &OrdererDefaults
    OrdererType: solo

    Addresses:
        - orderer.FinalExam.com:7050

    BatchTimeout: 2s

    BatchSize:

        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB

    Organizations:


Application: &ApplicationDefaults
    Organizations:
    