OrdererOrgs:
  - Name: Orderer
    Domain: finalexam.com
    Specs:
      - Hostname: orderer
PeerOrgs:
  - Name: Org1
    Domain: Org1.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: Org2.com
    Template:
      Count: 2
    Users:
      Count: 1