OrdererOrgs:
  - Name: Orderer
    Domain: finalexam.com
    Specs:
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
PeerOrgs:
  - Name: Org1
    Domain: Org1.com
    Template:
      Count: 2
    Users:
      Count: 1
  - Name: Org2
    Domain: Org2.com
    Template:
      Count: 2
    Users:
      Count: 1