version: '2'

networks:
  finalexam:

services:
  zookeeper0:
    container_name: zookeeper0
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - finalexam

  zookeeper1:
    container_name: zookeeper1
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - finalexam

  zookeeper2:
    container_name: zookeeper2
    extends:
      file: kafka.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2888:3888 server.2=zookeeper1:2888:3888 server.3=zookeeper2:2888:3888
    networks:
      - finalexam

  kafka0:
    container_name: kafka0
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 9092:9092
    networks:
      - finalexam

  kafka1:
    container_name: kafka1
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 10092:9092
    networks:
      - finalexam

  kafka2:
    container_name: kafka2
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 11092:9092
    networks:
      - finalexam

  kafka3:
    container_name: kafka3
    extends:
      file: kafka.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
    ports:
      - 12092:9092
    networks:
      - finalexam  
    
  orderer0.finalexam.com:
    container_name: orderer0.finalexam.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/finalexam.com/orderers/orderer0.finalexam.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - finalexam

  orderer1.finalexam.com:
    container_name: orderer1.finalexam.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/finalexam.com/orderers/orderer1.finalexam.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - finalexam

  orderer2.finalexam.com:
    container_name: orderer2.finalexam.com
    extends:
      file: orderer.yaml
      service: orderer
    volumes:
      - ./crypto-config/ordererOrganizations/finalexam.com/orderers/orderer2.finalexam.com/msp:/var/hyperledger/orderer/msp
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2
      - kafka0
      - kafka1
      - kafka2
      - kafka3
    networks:
      - finalexam

  peer0.Org1.com:
    container_name: peer0.Org1.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Org1.com
      - CORE_PEER_ADDRESS=peer0.Org1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org1.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org1.com/peers/peer0.Org1.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer0.finalexam.com
      - orderer1.finalexam.com
      - orderer2.finalexam.com
    networks:
      - finalexam

  peer1.Org1.com:
    container_name: peer1.Org1.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.Org1.com
      - CORE_PEER_ADDRESS=peer1.Org1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org1.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org1.com/peers/peer1.Org1.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 7052:7052
      - 7054:7054
    depends_on:
      - orderer0.finalexam.com
      - orderer1.finalexam.com
      - orderer2.finalexam.com
    networks:
      - finalexam

  peer0.Org2.com:
    container_name: peer0.Org2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Org2.com
      - CORE_PEER_ADDRESS=peer0.Org2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org2.com/peers/peer0.Org2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer0.finalexam.com
      - orderer1.finalexam.com
      - orderer2.finalexam.com
    networks:
      - finalexam

  peer1.Org2.com:
    container_name: peer1.Org2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.Org2.com
      - CORE_PEER_ADDRESS=peer1.Org2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer/
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org2.com/peers/peer1.Org2.com/msp:/etc/hyperledger/msp/peer
    ports:
      - 8052:7052
      - 8054:7054
    depends_on:
      - orderer0.finalexam.com
      - orderer1.finalexam.com
      - orderer2.finalexam.com
    networks:
      - finalexam
  
  cli.Org1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Org1
    environment:
      - CORE_PEER_ID=cli.Org1.com
      - CORE_PEER_ADDRESS=peer0.Org1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Org1.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Org1.com:/etc/hyperledger/msp
    depends_on:
      - peer0.Org1.com
    networks:
      - finalexam

  cli.Org2:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Org2
    environment:
      - CORE_PEER_ID=cli.Org2.com
      - CORE_PEER_ADDRESS=peer0.Org2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Org2.com/msp
    volumes:
      - ./crypto-config/peerOrganizations/Org2.com:/etc/hyperledger/msp
    depends_on:
      - peer0.Org2.com
    networks:
      - finalexam
