version: '2'

networks:
  finalexam:

services:
  orderer.finalexam.com:
    image: hyperledger/fabric-orderer:x86_64-1.1.0
    container_name: orderer.finalexam.com
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/var/hyperledger/orderer/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
    volumes:
      - ./orderer/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ./crypto-config/ordererOrganizations/finalexam.com/orderers/orderer.finalexam.com/msp:/var/hyperledger/orderer/msp
      - ./crypto-config/ordererOrganizations/finalexam.com/orderers/orderer.finalexam.com/tls:/var/hyperledger/orderer/tls
    command: orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      - finalexam

  peer0.Org1.com:
    container_name: peer0.Org1.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Org1.com
      - CORE_PEER_ADDRESS=peer0.Org1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org1.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org1.com/peers/peer0.Org1.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/Org1.com/peers/peer0.Org1.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7051:7051
      - 7053:7053
    depends_on:
      - orderer.finalexam.com
    networks:
      - finalexam

  peer1.Org1.com:
    container_name: peer1.Org1.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.Org1.com
      - CORE_PEER_ADDRESS=peer1.Org1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org1.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org1.com/peers/peer1.Org1.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/Org1.com/peers/peer1.Org1.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 7052:7052
      - 7054:7054
    depends_on:
      - orderer.finalexam.com
    networks:
      - finalexam

  peer0.Org2.com:
    container_name: peer0.Org2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer0.Org2.com
      - CORE_PEER_ADDRESS=peer0.Org2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.Org2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org2.com/peers/peer0.Org2.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/Org2.com/peers/peer0.Org2.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8051:7051
      - 8053:7053
    depends_on:
      - orderer.finalexam.com
    networks:
      - finalexam

  peer1.Org2.com:
    container_name: peer1.Org2.com
    extends:
      file: ./peer.yaml
      service: peer
    environment:
      - CORE_PEER_ID=peer1.Org2.com
      - CORE_PEER_ADDRESS=peer1.Org2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/fabric/msp
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.Org2.com:7051
    volumes:
      - ./crypto-config/peerOrganizations/Org2.com/peers/peer1.Org2.com/msp:/etc/hyperledger/fabric/msp
      - ./crypto-config/peerOrganizations/Org2.com/peers/peer1.Org2.com/tls:/etc/hyperledger/fabric/tls
    ports:
      - 8052:7052
      - 8054:7054
    depends_on:
      - orderer.finalexam.com
    networks:
      - finalexam
  
  cli.Org1:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Org1
    environment:
      - CORE_PEER_ID=cli.Org1.com
      - CORE_PEER_ADDRESS=peer0.Org1.com:7051
      - CORE_PEER_LOCALMSPID=Org1MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Org1.com/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Org1.com/peers/peer0.Org1.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Org1.com/peers/peer0.Org1.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Org1.com/peers/peer0.Org1.com/tls/ca.crt
    volumes:
      - ./crypto-config/peerOrganizations/Org1.com:/etc/hyperledger/msp
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
      - orderer.finalexam.com
      - peer0.Org1.com
    networks:
      - finalexam

  cli.Org2:
    extends:
      file: ./cli.yaml
      service: cli
    container_name: cli.Org2
    environment:
      - CORE_PEER_ID=cli.Org2.com
      - CORE_PEER_ADDRESS=peer0.Org2.com:7051
      - CORE_PEER_LOCALMSPID=Org2MSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/users/Admin@Org2.com/msp
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Org2.com/peers/peer0.Org2.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Org2.com/peers/peer0.Org2.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/Org2.com/peers/peer0.Org2.com/tls/ca.crt
    volumes:
      - ./crypto-config/peerOrganizations/Org2.com:/etc/hyperledger/msp
      - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
    depends_on:
      - orderer.finalexam.com
      - peer0.Org2.com
    networks:
      - finalexam
